### ISSUE TITLE
Recommendations

### ISSUE THREAD

**Issue by nicholasc** [PawelBis/bevy_wry#1]
Hi,

I was looking to do something similar to this project and this repository sent me in the right direction for some investigation on how to properly integrate `bevy` and `wry`. I've found a few caveats I believe you should be aware for if you ever feel like pursuing this project.:

**1. winit transparency issue on Windows**
Current releases of `winit` do not support WS_CLIPCHILDREN and therefore let `wry` transparency go through whatever is being rendered behind in the WebView. Control on this will be part of a [future release](https://github.com/rust-windowing/winit/blob/4cd6877e8e19e7e1ba957a409394dca1af4afcdd/src/platform/windows.rs#L370) of `winit` and will have to be supported by `bevy_winit` in order for `bevy_wry` to properly to work on Windows.

**2. Use wry's IPC instead of WebSocket**
`wry` offers a secure request/response based [IPC channel](https://docs.rs/wry/latest/wry/struct.WebViewBuilder.html#method.with_ipc_handler) (which is the communication method used by `tauri`) between the WebView's Javascript process and the Rust process. I believe this communication method should be leveraged instead of a custom websocket connection.

Cheers.

**Comment by PawelBis** [comment]
Hi!

Thank you for a great input. I was not aware of this IPC channel. l refactored this plugin so it uses IPC channel for incoming events and `WebView::evaluate_script` for outgoing events.

As for 1 - I will have to play with this plugin on Windows more.
