### ISSUE TITLE
Crash on Example

### ISSUE THREAD

**Issue by mwbryant** [PawelBis/bevy_wry#2]
OS Ubuntu 22.04 crashes on the example with
```
GDK has not been initialized. Call `gdk::init` or `gtk::init` first.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Encountered a panic in system `bevy_wry::setup_webview<simple::Command, simple::Command>`!
Encountered a panic in system `bevy_app::main_schedule::Main::run_main`!
```

**Comment by fgadaleta** [comment]
Same here

**Comment by PawelBis** [comment]
Thanks for the report.

I don't have an access to Linux machine ATM, but I believe that it should be fixed now (X11 only). The caveat is that there is an [issue](https://github.com/tauri-apps/wry/issues/1319): winit + wry transparency doesn't work properly on linux.

To work around that I added an Anchor + multi webview support, so now you can use webviews as widgets.

Also, I replaced the `simple` example with `fullscreen` and `anchor` examples.
